0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,26 @@
-#!/usr/bin/env bash
-# This is a bash script that transfers a file from a client to a server using scp
+#!/bin/bash
 
-if [ "$#" -lt 3 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+# Check if the number of parameters is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+path_file_path=$1
+server_ip=$2
+username=$3
+path_to_key_path=$4
+
+# Disable strict host key checking for scp
+export SSHPASS="yes"
+
+# Transfer the file using scp
+scp -o "StrictHostKeyChecking=no" -i "$path_ssh_key_path" "$path_file_path" "$username"@"$username@ip:~/"
+
+# Check if the scp command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transfer successful"
 else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+    echo "Error transferring file"
 fi
